### ISSUE TITLE
Realtime station link broken

### ISSUE THREAD

**Issue by Janewyx** [bcgov/nbcclim#2]
@bevingtona The link for Hourglass real time weather station is broken, most likely, it is the Data Garrison link that's been altered. Thanks for investigating.

`An error has occurred. Check your logs or contact the app author for clarification.`

**Comment by bevingtona** [comment]
@Janewyx  Indeed! I will look into it. thx

They are all up to date with realtime values now though - cool eh?

**Comment by bevingtona** [comment]
found it, column name issue! GitHub and ShinyApp are up to date :)
